version: '3.7'
services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    image: lifemaxx_client
    container_name: lifemaxx_client_container
    volumes:
      - ./client/:/usr/src/lifemaxx/client/
      - /usr/src/lifemaxx/client/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - lifemaxx_network
    # restart: always
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lifemaxx_server
    container_name: lifemaxx_server_container
    restart: always
    volumes:
      - ./:/usr/src/lifemaxx/server/
      - /usr/src/lifemaxx/server/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/lifemaxx
      - CHOKIDAR_USEPOLLING=true
    networks:
      - lifemaxx_network 
  mongo:
    image: mongo
    restart: always
    container_name: lifemaxx_mongo_container
    ports:
      - '27017:27017'
    networks:
      - lifemaxx_network
    volumes:
      - data_mongo:/data/db

networks:
  lifemaxx_network:
      driver: bridge
    
volumes:
    data_mongo:
    node_modules_client:
    node_modules_server:
    web-root:
      driver: local